services:
  mysql-db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=emp_db
      - MYSQL_USER=mysql_username
      - MYSQL_PASSWORD=mysql_password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root --password=root"]
      interval: 10s
      retries: 5
      start_period: 30s

  react-app:
    image: ansudock/employee-management-react
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BOOKSTORE_URL=http://spring-boot-app:8080
    networks:
      - my-network

  spring-boot-app:
    image: ansudock/employee-management-springboot
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/emp_db
      - SPRING_DATASOURCE_USERNAME=mysql_username
      - SPRING_DATASOURCE_PASSWORD=mysql_password
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - my-network

networks:
  my-network:

volumes:
  mysql-data:
